name: Checks
'on':
  push:
    branches:
      - main

jobs:
   Build:
     runs-on: ubuntu-latest

     steps:
       - name: Checkout-Repository
         uses: actions/checkout@v4

       - name: Setup Go
         uses: actions/setup-go@v5.5.0
         with:
           go-version: "1.24.3"
           check-latest: true
           cache-dependency-path: |
             go.sum
           
       - name: Build App
         working-directory: main/
         run: go build -o gofetch .

       - name: Upload
         uses: actions/upload-artifact@v4
         with:
           name: gofetch
           path: main/gofetch
